
# Menu tree
menu_tree = {1: "ekstrudiranje",
            11: "ZSK43",
            110: "ekstrudiranje",
            111: "čišćenje",
            112: "čišćenje radnog mesta",
            113: "čekanje probe sa mlina",
            114: "kontrola",
            115: "kvar",
            116: "nema premiksa",
            1160: "korekcija",
            1161: "nema premiksa",
            1162: "nema sirovine",
            117: "nema konejnera za čips",
            118: "zagrevanje",
            119: "nema operatera",
            12: "APV",
            120: "ekstrudiranje",
            121: "čišćenje",
            122: "čišćenje radnog mesta",
            123: "čekanje probe sa mlina",
            124: "kontrola",
            125: "kvar",
            126: "nema premiksa",
            1260: "korekcija",
            1261: "nema premiksa",
            1262: "nema sirovine",
            127: "nema konejnera za čips",
            128: "zagrevanje",
            129: "nema operatera",
            2: "mlevenje",
            21: "ACM20",
            210: "mlevenje",
            211: "čišćenje",
            212: "čišćenje radnog mesta",
            213: "kontrola",
            214: "kvar",
            215: "nema čipsa",
            216: "pražnjenje filtera",
            217: "nema operatera",
            22: "ACM30",
            220: "mlevenje",
            221: "čišćenje",
            222: "čišćenje radnog mesta",
            223: "kontrola",
            224: "kvar",
            225: "nema čipsa",
            226: "pražnjenje filtera",
            227: "nema operatera",
            3: "šaržiranje",
            30: "ubacivanje premiksa",
            31: "mešanje premiksa"
      }

# breakdown_tree
breakdown_tree = {"E1": "stanica za istakanje",
                "E11": "pneumatika",
                "E111": "creva",
                "E112": "spojnice",
                "E112": "elektroormar",
                "E12": "ručica za otvaranje kontejnera",
                "E121": "ručica na stanici za istakanje",
                "E122": "ručica na kontejneru",
                "E13": "tresač",
                "E131": "vibromotor",
                "E132": "elektroormar",
                "E14": "cev",
                "E141": "zaptivna guma",
                "E2": "dozirni koš",
                "E21": "motor",
                "E22": "spirala",
                "E23": "mehanizam",
                "E3": "pogonski mehanizam",
                "E31": "motor za šneke",
                "E32": "reduktor",
                "E33": "spojnica",
                "E34": "šneke",
                "E341": "zamena šnjura",
                "E342": "zakovale šneke",
                "E343": "stale šneke - viskoa T u el ormaru na APVu??",
                "E4": "temperaturne zone",
                "E41": "zagrevanje zona",
                "E411": "grejač",
                "E42": "hlađenje zona",
                "E421": "elektromagnetni ventil",
                "E422": "crevo za rashladnu vodu",
                "E423": "agregat sa destilovanom vodom",
                "E5": "rashladna traka",

                "E9": "Ostalo",
                "E91": "lift",
                "E92": "nestanak struje",
                "E93": "ventilacija",
                "E94": "komprimovani vazduh",
                "E95": "Mešač",
                "E96": "kontrolna tabla",
                "M1": "doziranje čipsa",
                "M2": "doziranje aditiva",
                "M3": "mlin",
                "M4": "ciklon",
                "M5": "filter",
                "M6": "separator",
                "M7": "istakanje",
                "M8": "ventilator",
                "M9": "ostalo",
                "M91": "rashladni uređaj za ulazni vazduh",
                "M92": "nestanak struje",
                "M93": "ventilacija",
                "M94": "dizalica",
                "M95": "senzor"

}
